#### Generate Direct Estimation Table for Manuscript ####
# Created: 2026-01-23
# Purpose: Generate tbl_df_DIR.tex for manuscript - multimodal direct estimates summary
# Updates the hardcoded table in manuscript with actual data

rm(list = ls())
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, xtable)

# Data path
data_path <- "./data"
output_dir <- "./manuscript"

#### Load Data ####
df_direct <- readRDS(file.path(data_path, "output/direct/df_HTH_perskm_analytical.rds"))

# Calculate CV (as proportion, not percentage)
df_direct <- df_direct %>%
  mutate(cv_hth = se_hth / perskm_hth)

cat("=== Data loaded successfully ===\n")
cat("Total domains:", nrow(df_direct), "\n")
cat("Districts:", n_distinct(df_direct$ags5), "\n")
cat("Modes:", paste(unique(df_direct$hvm_label), collapse = ", "), "\n\n")

#### Summary Statistics by Mode ####

# Calculate summary statistics for each mode
summary_by_mode <- df_direct %>%
  group_by(hvm_label) %>%
  summarise(
    Min_perskm = min(perskm_hth, na.rm = TRUE),
    Q1_perskm = quantile(perskm_hth, 0.25, na.rm = TRUE),
    Median_perskm = median(perskm_hth, na.rm = TRUE),
    Mean_perskm = mean(perskm_hth, na.rm = TRUE),
    Q3_perskm = quantile(perskm_hth, 0.75, na.rm = TRUE),
    Max_perskm = max(perskm_hth, na.rm = TRUE),
    Min_cv = min(cv_hth, na.rm = TRUE),
    Q1_cv = quantile(cv_hth, 0.25, na.rm = TRUE),
    Median_cv = median(cv_hth, na.rm = TRUE),
    Mean_cv = mean(cv_hth, na.rm = TRUE),
    Q3_cv = quantile(cv_hth, 0.75, na.rm = TRUE),
    Max_cv = max(cv_hth, na.rm = TRUE),
    # Sample size statistics (Panel C) - use n_with_trips (persons with trips of that mode)
    # n_with_trips varies by mode; n_obs is the same for all modes (total persons per district)
    Min_n = min(n_with_trips, na.rm = TRUE),
    Q1_n = quantile(n_with_trips, 0.25, na.rm = TRUE),
    Median_n = median(n_with_trips, na.rm = TRUE),
    Mean_n = mean(n_with_trips, na.rm = TRUE),
    Q3_n = quantile(n_with_trips, 0.75, na.rm = TRUE),
    Max_n = max(n_with_trips, na.rm = TRUE),
    n_zero_trips = sum(n_with_trips == 0, na.rm = TRUE),
    n_domains = n(),
    n_cv_above_20 = sum(cv_hth > 0.20, na.rm = TRUE),
    pct_cv_above_20 = 100 * mean(cv_hth > 0.20, na.rm = TRUE),
    .groups = "drop"
  )

cat("=== Summary Statistics by Mode ===\n")
print(summary_by_mode)

cat("\n=== Sample Size Summary (n_with_trips = persons who traveled by that mode) ===\n")
cat("Domains with zero trips (in current data):", sum(df_direct$n_with_trips == 0, na.rm = TRUE), "\n")
cat("Note: 10 out-of-sample domains were excluded before this stage (see manuscript Section 2.1)\n")
cat("Min n_with_trips:", min(df_direct$n_with_trips, na.rm = TRUE), "\n")
cat("Max n_with_trips:", max(df_direct$n_with_trips, na.rm = TRUE), "\n")
cat("Median n_with_trips:", median(df_direct$n_with_trips, na.rm = TRUE), "\n")

#### Generate LaTeX Table ####

# Prepare table data - one row per mode with perskm and CV statistics
tbl_data <- summary_by_mode %>%
  mutate(
    Mode = case_when(
      hvm_label == "fuss" ~ "Walking",
      hvm_label == "fahrrad" ~ "Cycling",
      hvm_label == "miv" ~ "Car (MIV)",
      hvm_label == "oepv" ~ "Public Transit"
    )
  ) %>%
  select(Mode,
         Min_perskm, Q1_perskm, Median_perskm, Mean_perskm, Q3_perskm, Max_perskm,
         Min_cv, Q1_cv, Median_cv, Mean_cv, Q3_cv, Max_cv,
         Min_n, Q1_n, Median_n, Mean_n, Q3_n, Max_n, n_zero_trips,
         n_domains, n_cv_above_20, pct_cv_above_20)

# Format numeric values
format_val <- function(x, digits = 2) {
  sprintf(paste0("%.", digits, "f"), x)
}

# Create table for perskm statistics
tbl_perskm <- tbl_data %>%
  transmute(
    Mode = Mode,
    Min = format_val(Min_perskm),
    `1st Qu.` = format_val(Q1_perskm),
    Median = format_val(Median_perskm),
    Mean = format_val(Mean_perskm),
    `3rd Qu.` = format_val(Q3_perskm),
    Max = format_val(Max_perskm)
  )

# Create table for CV statistics
tbl_cv <- tbl_data %>%
  transmute(
    Mode = Mode,
    Min = format_val(Min_cv),
    `1st Qu.` = format_val(Q1_cv),
    Median = format_val(Median_cv),
    Mean = format_val(Mean_cv),
    `3rd Qu.` = format_val(Q3_cv),
    Max = format_val(Max_cv)
  )

# Create table for sample size statistics (Panel C)
tbl_n <- tbl_data %>%
  transmute(
    Mode = Mode,
    Min = format_val(Min_n, digits = 0),
    `1st Qu.` = format_val(Q1_n, digits = 0),
    Median = format_val(Median_n, digits = 0),
    Mean = format_val(Mean_n, digits = 0),
    `3rd Qu.` = format_val(Q3_n, digits = 0),
    Max = format_val(Max_n, digits = 0)
  )

# Count domains with zero trips (out-of-sample for that mode)
n_zero_trip_domains <- sum(df_direct$n_with_trips == 0, na.rm = TRUE)

#### Write LaTeX Output ####

# Write combined table as LaTeX
latex_output <- c(
  "% LaTeX table generated by R/plotting/generate_direct_estimation_table.r",
  paste0("% Generated: ", Sys.time()),
  "\\begin{table}[ht]",
  "\\centering",
  "\\begin{tabularx}{\\textwidth}{lXXXXXX}",
  "\\hline",
  "\\multicolumn{7}{c}{\\textbf{Panel A: Direct Estimates (km/day)}} \\\\",
  "\\hline",
  "\\textbf{Mode} & \\textbf{Min.} & \\textbf{1st Qu.} & \\textbf{Median} & \\textbf{Mean} & \\textbf{3rd Qu.} & \\textbf{Max.} \\\\"
)

# Add perskm rows
for (i in 1:nrow(tbl_perskm)) {
  latex_output <- c(latex_output,
    paste0(tbl_perskm$Mode[i], " & ",
           tbl_perskm$Min[i], " & ",
           tbl_perskm$`1st Qu.`[i], " & ",
           tbl_perskm$Median[i], " & ",
           tbl_perskm$Mean[i], " & ",
           tbl_perskm$`3rd Qu.`[i], " & ",
           tbl_perskm$Max[i], " \\\\"))
}

latex_output <- c(latex_output,
  "\\hline",
  "\\multicolumn{7}{c}{\\textbf{Panel B: Coefficient of Variation}} \\\\",
  "\\hline",
  "\\textbf{Mode} & \\textbf{Min.} & \\textbf{1st Qu.} & \\textbf{Median} & \\textbf{Mean} & \\textbf{3rd Qu.} & \\textbf{Max.} \\\\"
)

# Add CV rows
for (i in 1:nrow(tbl_cv)) {
  latex_output <- c(latex_output,
    paste0(tbl_cv$Mode[i], " & ",
           tbl_cv$Min[i], " & ",
           tbl_cv$`1st Qu.`[i], " & ",
           tbl_cv$Median[i], " & ",
           tbl_cv$Mean[i], " & ",
           tbl_cv$`3rd Qu.`[i], " & ",
           tbl_cv$Max[i], " \\\\"))
}

# Add Panel C: Sample Sizes
latex_output <- c(latex_output,
  "\\hline",
  "\\multicolumn{7}{c}{\\textbf{Panel C: Domain Sample Sizes (persons)}} \\\\",
  "\\hline",
  "\\textbf{Mode} & \\textbf{Min.} & \\textbf{1st Qu.} & \\textbf{Median} & \\textbf{Mean} & \\textbf{3rd Qu.} & \\textbf{Max.} \\\\"
)

# Add sample size rows
for (i in 1:nrow(tbl_n)) {
  latex_output <- c(latex_output,
    paste0(tbl_n$Mode[i], " & ",
           tbl_n$Min[i], " & ",
           tbl_n$`1st Qu.`[i], " & ",
           tbl_n$Median[i], " & ",
           tbl_n$Mean[i], " & ",
           tbl_n$`3rd Qu.`[i], " & ",
           tbl_n$Max[i], " \\\\"))
}

latex_output <- c(latex_output,
  "\\hline",
  "\\hline",
  "\\end{tabularx}",
  paste0("\\caption{Summary statistics of multimodal \\ac{HJ} direct estimates. ",
         "Panel A: person-kilometers per day. ",
         "Panel B: coefficient of variation (CV). ",
         "Panel C: domain sample sizes (persons with at least one trip by that mode). ",
         "Total domains: ", nrow(df_direct), " (", n_distinct(df_direct$ags5), " districts $\\times$ 4 modes), ",
         "of which ", n_zero_trip_domains, " have zero observations for that mode.}"),
  "\\label{tbl:df_DIR}",
  "\\end{table}"
)

# Write to file
writeLines(latex_output, file.path(output_dir, "tbl_df_DIR.tex"))

cat("\n=== LaTeX table saved to:", file.path(output_dir, "tbl_df_DIR.tex"), "===\n")

#### Also generate precision summary ####

precision_summary <- tbl_data %>%
  select(Mode, n_domains, n_cv_above_20, pct_cv_above_20)

cat("\n=== Precision Summary (CV > 20%) ===\n")
print(precision_summary)

# Write precision summary as separate table
latex_precision <- c(
  "% LaTeX table generated by R/plotting/generate_direct_estimation_table.r",
  paste0("% Generated: ", Sys.time()),
  "\\begin{table}[ht]",
  "\\centering",
  "\\begin{tabularx}{\\textwidth}{lXXX}",
  "\\hline",
  "\\textbf{Mode} & \\textbf{Domains} & \\textbf{CV $>$ 20\\%} & \\textbf{\\% Low Precision} \\\\",
  "\\hline",
  "\\hline"
)

for (i in 1:nrow(precision_summary)) {
  latex_precision <- c(latex_precision,
    paste0(precision_summary$Mode[i], " & ",
           precision_summary$n_domains[i], " & ",
           precision_summary$n_cv_above_20[i], " & ",
           sprintf("%.1f", precision_summary$pct_cv_above_20[i]), "\\% \\\\"))
}

# Add total row (use mean(na.rm=TRUE) to exclude NaN zero-trip domains, consistent with per-mode %)
total_domains <- sum(precision_summary$n_domains)
total_low_precision <- sum(precision_summary$n_cv_above_20)
total_pct <- 100 * mean(df_direct$cv_hth > 0.20, na.rm = TRUE)

latex_precision <- c(latex_precision,
  "\\hline",
  paste0("\\textbf{Total} & ", total_domains, " & ", total_low_precision, " & ",
         sprintf("%.1f", total_pct), "\\% \\\\"),
  "\\hline",
  "\\hline",
  "\\end{tabularx}",
  "\\caption{Precision of direct estimates by transport mode. Low precision domains are those with CV $>$ 20\\%.}",
  "\\label{tbl:df_DIR_precision}",
  "\\end{table}"
)

writeLines(latex_precision, file.path(output_dir, "tbl_df_DIR_precision.tex"))

cat("\n=== Precision table saved to:", file.path(output_dir, "tbl_df_DIR_precision.tex"), "===\n")

cat("\n=== Done! ===\n")
